import '../support/commands/login.commands.js'
import '../support/commands/HomePage-CT005.commands.js'
import '../support/commands/cadastro.commands.js'
import '../support/commands/dataFaker.commands.js'
import '../support/commands/cadastro.commands.js'
import '../support/commands/home.commands.js'
