import '../support/commands/home.commands.js'
import '../support/commands/cadastro.commands.js'
import '../support/commands/login.commands.js'
import '../support/commands/transacao.commands.js'
import '../support/commands/meusDados.commands.js'
import '../support/commands/dataFaker.commands.js'
import '@shelex/cypress-allure-plugin'
